#! /bin/sh

# ~/scriptsC/lemon/script.sh | lemonbar -p -f "JetBrains Mono Nerd Font Mono" -12 -F "#ced4da" -B "#2b2d42" &
picom &
conky &
setxkbmap -layout us,ru &
setxkbmap -option 'grp:alt_shift_toggle' &
~/.config/polybar/launch.sh --material &
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config border_radius        10
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
#bspc rule -a nvim state=tiled
bspc rule -a telegram-desktop state=floating

bspc config normal_border_color "#D23D3D"
bspc config active_border_color "#ff0000" 
bspc config focused_border_color "#9079c7"
bspc config focused_border_color "#FFFFFF"

# $HOME/.config/polybar/launch.sh --forest
# sh -c /home/cyberdemon/scriptsC/lemon/script.sh | lemonbar -p -f "Iosevka Nerd Font"-10 -F "#d5c4a1" -B "#282828"

feh --bg-max ~/Pictures/wp2.jpg

